# Generated by Django 2.0.4 on 2018-07-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortstorylife', '0002_story_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
